version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: support_db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=support_db